[package]
name = "taimi_pack"
authors = [ "kittywitch" ]
description = "GW2 TacO packs"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
path = "src/lib.rs"

[[example]]
name = "print_pack"
path = "src/bin/print_pack.rs"

[lints]
workspace = true

[features]
default = [
  "zip",
  "fixup-typos",
]
serde = [
  "dep:serde",
]
zip = [
  "dep:zip",
]
fixup-typos = [
  "fixup-ladyelyssa",
  "fixup-tehstrails",
  "fixup-fvd",
]
fixup-ladyelyssa = []
fixup-tehstrails = []
fixup-fvd = []

[dependencies]
anyhow = "1"
strum = { workspace = true }
log = "0.4"
# TODO? tokio = { version = "1", features = [ "fs", "macros" ] }
glam = { workspace = true }
glamour = { workspace = true }
indexmap = { workspace = true }
relative-path = "1"
xml-rs = "0.8"
regex = "1"
uuid = { version = "1", features = ["v4"] }
md-5 = "0.10"
base64 = "0.22"
zip = { version = "4", optional = true }
bitvec = { workspace = true }
bitflags = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
env_logger = "0.11"
taimi_hoard = { path = "../../rt/hoard" }
