[workspace]
resolver = "3"
members = [
  "pathing/pack",
  "pathing/meta",
  "rt/hoard",
  "rt/input",
  "rt/sync",
  "space/d3d",
]

[package]
name = "taimi_hud"
authors = [
  "kittywitch",
  "Connicpu",
  "arcnmx"
]
homepage = "https://taimihud.com"
description = "Pathing, encounter timers and markers"
version = "0.3.3"
edition = "2021"
build = "build.rs"

[lints]
workspace = true

[features]
default = [
  "windows",
  "built-info",
  "timers",
  "markers",
  "markers-edit",
  "meta-cache",
  "space",
  "statistics",
  "extension-arcdps",
  "extension-nexus",
  "log-filter",
  "render-rt",
  "updates",
]
built-info = [
  #"built/chrono",
  "built/git2",
]

allocator = [
]
log-filter = ["dep:env_logger"]
render-rt = []
statistics = [
  "allocator",
]
updates = [
  "dep:semver",
]

space = [
  "dep:itertools",
  "dep:tobj",
  "dep:bevy_ecs",
  "dep:bevy_utils",
  "dep:arc-atomic",
  "windows/Win32_UI_WindowsAndMessaging",
  "windows/Win32_UI_Input_KeyboardAndMouse",
  "windows/Win32_Graphics_Direct3D11",
  "windows/Win32_Graphics_Dxgi",
  "windows/Win32_Graphics_Dxgi_Common",
  "windows/Win32_Graphics_Direct3D_Fxc",
  "windows/Win32_Graphics_Hlsl",
  "texture-loader",
  "goggles",
  "space-list",
  #"space-ecs",
  "dep:taimi_meta",
  "dep:taimi_pack",
  "dep:taimi_d3d",
]
space-ecs = [
]
space-list = [
  "dep:bvh",
  "dep:nalgebra",
]
goggles = [
  "dep:retour",
]

timers = [
]

markers = [
  "dep:itertools",
  "dep:arc-atomic",
  "dep:taimi_meta",
  "dep:taimi_input",
  "windows",
  "windows/System",
  "windows/Foundation",
  "windows/Win32_UI_WindowsAndMessaging",
  "windows/Win32_UI_Input_KeyboardAndMouse",
  "windows/Win32_Graphics_Gdi",
]
markers-edit = [
  "markers"
]

meta-cache = [
  "taimi_meta?/map-cache",
  "taimi_meta?/gzip",
]

extension-arcdps = [
  #"extension-arcdps-codegen",
  "extension-arcdps-extern",
  "extension-arcdps-extras",
  "dep:arcloader-mumblelink",
  "arcloader-mumblelink/gw2_mumble",
  "taimi_meta?/mumblelink-arcloader",
  "taimi_input?/arcdps-extras",
  "nexus/arc",
  "windows/Win32_System_LibraryLoader",
  "windows/Win32_System_Memory",
  "texture-loader",
]
extension-arcdps-extras = [
  "closure-ffi",
  "jit-allocator2",
  "nexus/extras",
  "windows/Win32_System_Memory",
  "windows/Win32_Security",
]
extension-arcdps-codegen = [
  "dpsapi",
  #"dpsapi/arcdps-015",
  "dpsapi/arcdps",
  "arcdps/export",
]
extension-arcdps-extern = [
  "dep:sync-unsafe-cell",
  "dpsapi",
  "dpsapi/embed",
  #"extension-arcdps-extern-cleanup"
  "arcffi",
]
extension-arcdps-extern-cleanup = [
]
extension-nexus = [
  "extension-nexus-codegen",
  #"extension-nexus-extern",
  "nexus/arc",
  "nexus/extras",
  "nexus/rtapi",
  "nexus/mumble",
  "taimi_meta?/nexus",
  "taimi_meta?/nexus-rtapi",
  "taimi_meta?/mumblelink-nexus",
]
extension-nexus-codegen = []
dpsapi = [
  "dep:dpsapi",
  "dpsapi/nexus",
]

arcffi = [
  "dep:arcffi",
  "taimi_d3d?/arcffi",
]
image = [
  "dep:image",
]
texture-loader = [
  "dep:taimi_d3d",
  "image",
  "windows/Win32_Graphics_Direct3D11",
  "windows/Win32_Graphics_Dxgi",
  "windows/Win32_Graphics_Dxgi_Common",
]
windows = [
  "dep:windows",
  "arcffi?/windows-061",
  #"dpsapi?/windows-061",
  "taimi_d3d?/windows",
  "taimi_input?/windows",
]

[lib]
crate-type = ["cdylib"] # nexus addons are dynamic system libraries (dll)
path = "src/lib.rs"

[workspace.lints.rust]
unconditional_recursion = { level = "deny" }
[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
  'cfg(todo, values("unused", "unnecessary"))',
  'cfg(todo)',
  'cfg(taimi_has, values("author", "title", "version"))',
  'cfg(taimi_debug)', 'cfg(taimi_debug, values("debug"))',
  'cfg(taimi_dev)', 'cfg(taimi_dev, values("debug", "drv", "ci", "branch"))',
  'cfg(taimi_release)', 'cfg(taimi_release, values("tag", "rc", "pre", "release"))',
]

[profile.release]
opt-level = "z"
#opt-level = 2
#codegen-units = 1
#debug = true
panic = "abort"
#lto = "thin"
lto = true

[build-dependencies]
built = { version = "0.7.7", default-features = false }
semver = "1"

[dependencies]
anyhow = "1"
env_logger = { version = "0.11", default-features = false, optional = true }
log = { version = "0.4", features = ["serde"] }
tokio = { version = "1.43.0", features = [ "fs", "macros" ], default-features = false }
arcdps = { workspace = true, features = ["extras", "strum"] }
glam = { workspace = true, features = [ "serde", "mint" ] }
glamour = { workspace = true, features = ["mint"] }
palette = { version = "0.7.6", features = [ "serde" ] }
serde = { version = "1.0", features = ["derive", "rc"] }
glob = "0.3.2"
serde_json = "1"
#serde_jsonrc = { version = "0.1.0", features = [ "preserve_order"] }
#serde_with = "3"
json-strip-comments = "1"
strum = { version = "0.27.1", features = ["derive"] }
reqwest = { version = "0.12.15", default-features = false, features = [ "stream", "rustls-tls-native-roots", "json" ] }
tempfile = "3.19.1"
bytes = "1.10.1"
async-compression = { version = "0.4.22", features = [ "tokio", "gzip" ] }
tokio-tar = "0.3.1"
tokio-stream = "0.1.17"
tokio-util = "0.7.14"
futures-core = "0.3.31"
futures = "0.3.31"
chrono = { version = "0.4.40", features = [ "serde", "alloc" ] }
indexmap = { workspace = true }
relative-path = { version = "1.9.3", features = [ "serde" ] }
bitflags = { workspace = true }
mint = "0.5.9"
itertools = { optional = true, version = "0.14.0" }
tobj = { optional = true, version = "4.0.3", features = [ "merging", "reordering" ] }
bevy_ecs = { optional = true, version = "0.16.0" }
bevy_utils = { optional = true, version = "0.16.0" }
arc-atomic = { optional = true, version = "0.1.0" }
url = { version = "2.5.4", features = ["serde"] }
lininterp = "0.1.3"
webpki-root-certs = "0.26.10"
open = "5.3.2"
function_name = "0.3.0"
magic_migrate = "1.1.0"
toml = "0.8.22"
serde_repr = "0.1.20"
i18n-embed = { version = "0.15.4", features = ["autoreload", "fluent-system"] }
fluent = "0.16.1"
fluent-syntax = "0.11"
rust-embed = { version = "8.7.1", features = [ "debug-embed" ] }
i18n-embed-fl = "0.9.4"
unic-langid-impl = "0.9.6"
rand = "0.9.1"
ordered-float = { version = "5.0.0", features = [ "serde" ] }
bvh = { version = "0.11.0", default-features = false, optional = true }
nalgebra = { version = "0.33", default-features = false, features = [ "convert-mint" ], optional = true }
semver = { version = "1", optional = true }
uuid = "1"
regex = "1"
croner = "3"
bitvec = { workspace = true }

taimi_pack = { path = "./pathing/pack", optional = true }
taimi_meta = { path = "./pathing/meta", optional = true, default-features = false, features = ["serde"] }
taimi_d3d = { path = "./space/d3d", optional = true, default-features = false, features = ["dx11", "serde"] }
taimi_input = { path = "./rt/input", optional = true, default-features = false, features = ["serde"] }
taimi_sync = { path = "./rt/sync", default-features = false, features = ["serde"] }
taimi_hoard = { path = "./rt/hoard", default-features = false, features = ["serde"] }

include_dir = { version = "0.7.4", features = ["glob"] }
retour = { version = "0.3", optional = true }
sync-unsafe-cell = { version = "0.1", optional = true }
closure-ffi = { version = "3", default-features = false, features = ["std"], optional = true }
jit-allocator2 = { version = "0.2", optional = true }

nexus = { workspace = true }
arcloader-mumblelink = { git = "https://github.com/arcnmx/arcloader", default-features = false, features = ["log", "identity"], optional = true }
arcffi = { git = "https://github.com/arcnmx/arcloader", default-features = false, optional = true }
dpsapi = { git = "https://github.com/arcnmx/arcloader", default-features = false, optional = true }

[dependencies.image]
optional = true
default-features = false
version = "0.25.6"
features = [
  "png",
  "jpeg",
  "tga",
  "tiff",
  "bmp",
  "dds",
]

[target.'cfg(windows)'.dependencies.windows]
optional = true
version = "0.61"
features = [
  "System",
  "Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Dxgi",
  "Win32_System_SystemServices"
]

[workspace.dependencies]
arcdps = { git = "https://github.com/zerthox/arcdps-rs" }
nexus = { git = "https://github.com/zerthox/nexus-rs" }
#gw2_mumble_nexus = { package = "gw2_mumble", git = "https://github.com/zerthox/gw2-mumble-rs", tag = "0.2.4", default-features = false }
glam = "0.30"
glamour = "0.18"
num-traits = { version = "0.2", default-features = false }
indexmap = "2.9"
bitvec = "1"
bitflags = "2"
# TODO: macro_rules_attribute = "0.2"

[patch."https://github.com/zerthox/arcdps-rs"]
# some fixes need to be contributed back upstream
arcdps = { git = "https://github.com/arcnmx/arcdps-rs" }
arcdps_codegen = { git = "https://github.com/arcnmx/arcdps-rs" }
evtc = { git = "https://github.com/arcnmx/arcdps-rs" }
